[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]
cwd = "/Users/andrejprus/Library/CloudStorage/Dropbox/projects/my-store"

[mcp_servers.herd]
command = "php"
args = ["/Applications/Herd.app/Contents/Resources/herd-mcp.phar"]
cwd = "/Users/andrejprus/Library/CloudStorage/Dropbox/projects/my-store"

[mcp_servers.herd.env]
SITE_PATH = "/Users/andrejprus/Library/CloudStorage/Dropbox/projects/my-store"
